### PR TITLE
improved UI and changed how locations are stored in database

### PR DESCRIPTION
**Pull request by neuoy**
Hello,

I'm using your flarum extension and had to make a few modifications to fit our forum needs. I thought you might be interested to get these modifications as I believe they improve the extension (that's up to you of course).

Multiple motivations for the modifications:
- immediately see on the map when a new location (city search) is entered in user settings
- allow to search by country, city name and/or postal code (to solve ambiguities since there are many duplicate city names in the world, and even often in the same country)
- reduce number of requests to nominatim (now only making a request when the user edits his location, not when viewing it, since latitude/longitude are stored in database)
- store latitude/longitude in database to allow geographic queries (retrieving all users in a rectangle) as we also plan to display a map of all users of our forum

In any case, thanks a lot for this extension!

### CODE REVIEW

**Comment by justoverclockl** [comment]
thank you for your contribution, i will try your version asap

**Comment by justoverclockl** [comment]
when i'm saving the fields i get an error:

```
POST http://localhost/flarum-12/flarum/public/api/users/1

<br />
<b>Notice</b>:  Undefined index: location_postcode in <b>E:\Xampp\htdocs\flarum-12\flarum\workbench\users-map-location\src\Listeners\SaveLocationToDatabase.php</b> on line <b>33</b><br />
<br />
<b>Fatal error</b>:  Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in E:\Xampp\htdocs\flarum-12\flarum\vendor\laminas\laminas-httphandlerrunner\src\Exception\EmitterException.php:24
Stack trace:
#0 E:\Xampp\htdocs\flarum-12\flarum\vendor\laminas\laminas-httphandlerrunner\src\Emitter\SapiEmitterTrait.php(40): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent()
#1 E:\Xampp\htdocs\flarum-12\flarum\vendor\laminas\laminas-httphandlerrunner\src\Emitter\SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter-&gt;assertNoPreviousOutput()
#2 E:\Xampp\htdocs\flarum-12\flarum\vendor\laminas\laminas-httphandlerrunner\src\RequestHandlerRunner.php(98): Laminas\HttpHandlerRunner\Emitter\SapiEmitter-&gt;emit(Object(Flarum\Api\JsonApiResponse))
#3 E:\Xampp\htdocs\flarum-12\flarum\vendor\flarum\core\src\Http\Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner-&gt;run()
#4 E:\Xampp\htdocs\flarum-12\flarum\public\index.php(26): Flarum\Http\Server in <b>E:\Xampp\htdocs\flarum-12\flarum\vendor\laminas\laminas-httphandlerrunner\src\Exception\EmitterException.php</b> on line <b>24</b><br />
```

**Comment by justoverclockl** [comment]
nevermind i figured why, i have two migrations, il will check well your work. can you submit again your pr please?

**Comment by justoverclockl** [comment]
it works apparently but i get some errors on submit

xD7FK2pGgN

https://i.ibb.co/rm3QVKN/x-D7-FK2p-Gg-N.gif

if you can fix this i will merge

**Comment by neuoy** [comment]
this is weird, I did not manage to reproduce this issue. I have also installed the extension on a fresh flarum server, and I have no error.

Have you checked the database has correctly been updated by the migrations? (does column location_postcode exist in the database?)

I don't know what is going wrong, maybe if you can provide me the complete error message it could help? It's truncated in your video capture.

Thanks.

**Comment by justoverclockl** [comment]
Try with my city:

country: Italy
City name: Cellamare

**Comment by neuoy** [comment]
I tried to do exactly as in the video, but did not get any error.

**Comment by justoverclockl** [comment]
unfortunately, i have this error, so i can't merge at moment. I've removed my extension, clear database column. but i can replicate this error everytime.

with my extension all works fine.

**Pull request merged**
